name: Build examples

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vita-rust/vitasdk-rs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Northfear SDL fork
        run: |
          chown -R 1000:1000 northfear-sdl2
          cd northfear-sdl2
          sudo --preserve-env=VITASDK -u \#1000 vita-makepkg
          vdpm sdl2-2.30.2-1-arm.tar.xz
      - name: Build
        run: |
          cargo vita build vpk --release --package vita-std-tests --tests
          cargo vita build vpk --release
          mv target/armv7-sony-vita-newlibeabihf/release/deps/*.vpk target/armv7-sony-vita-newlibeabihf/release/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: examples
          path: target/armv7-sony-vita-newlibeabihf/release/*.vpk
